### ISSUE TITLE
No provider for WindowRef! Error

### ISSUE THREAD

**Issue by mackelito** [DineroRegnskab/ngx-virtual-scroll#3]
Gave this a try and getting `Error: Uncaught (in promise): Error: No provider for WindowRef!`

**Comment by mikkeldamm** [comment]
@mackelito the directive have a dependency for WindowRef, which is inside the module as well. So to make it work, you need to import the ngx-virtual-scroll in this way:
```
@NgModule({
    imports: [
        ...,
        NgxVirtualScrollModule.forRoot()
    ]
})
```
You could also just import it as normal, but then you need to provide the `WindowRef` dependency your self.
```
import { WindowRef } from 'ngx-virtual-scroll';

@NgModule({
    providers: [
        { provide: WindowRef: useClass: YourOwnWindowRefClass }
    ]
});
```
